/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ChorusCharts {
  album_art_md5: string | null;
  artist: string;
  artist_bucket: string | null;
  artist_normalized: string | null;
  charter: string;
  charter_normalized: string | null;
  diff_bass: number | null;
  diff_drums: number | null;
  diff_drums_real: number | null;
  diff_guitar: number | null;
  diff_keys: number | null;
  group_id: number;
  has_video_background: number;
  md5: string;
  modified_time: string;
  name: string;
  name_normalized: string | null;
  song_length: number | null;
}

export interface ChorusMetadata {
  key: string | null;
  updated_at: Generated<string>;
  value: string;
}

export interface ChorusScanSessions {
  completed_at: string | null;
  id: Generated<number | null>;
  last_chart_id: number | null;
  scan_since_time: string;
  started_at: string;
  status: string;
}

export interface LocalCharts {
  artist: string;
  artist_bucket: string | null;
  artist_normalized: string | null;
  charter: string;
  charter_normalized: string | null;
  data: string;
  id: Generated<number | null>;
  modified_time: string;
  song: string;
  song_normalized: string | null;
  updated_at: string;
}

export interface SpotifyAlbums {
  artist_name: string;
  id: string;
  name: string;
  total_tracks: Generated<number>;
  updated_at: string;
}

export interface SpotifyAlbumTracks {
  album_id: string;
  track_id: string;
  updated_at: string;
}

export interface SpotifyPlaylists {
  collaborative: Generated<number>;
  id: string;
  name: string;
  owner_display_name: string;
  owner_external_url: string;
  snapshot_id: string;
  total_tracks: Generated<number>;
  updated_at: string;
}

export interface SpotifyPlaylistTracks {
  playlist_id: string;
  track_id: string;
}

export interface SpotifyTracks {
  artist: string;
  artist_bucket: string | null;
  artist_normalized: string | null;
  id: string;
  name: string;
  name_normalized: string | null;
  updated_at: string;
}

export interface SpotifyTrackChartMatches {
  spotify_id: string;
  chart_md5: string;
  matched_at: number;
}

export interface SpotifyHistory {
  artist: string;
  artist_normalized: string;
  name: string;
  name_normalized: string;
  play_count: number;
  last_played: string | null;
  ms_played: Generated<number>;
}

export interface SpotifyHistoryImports {
  id: Generated<number>;
  filename: string;
  file_size: number;
  imported_at: string;
}

export interface SavedCharts {
  md5: string;
  name: string;
  artist: string;
  charter: string;
  album_art_md5: string | null;
  diff_drums: number | null;
  diff_drums_real: number | null;
  diff_guitar: number | null;
  diff_bass: number | null;
  diff_keys: number | null;
  song_length: number | null;
  has_video_background: number;
  modified_time: string;
  saved_at: string;
  is_downloaded: Generated<number>;
  tab_url: string | null;
}

export interface Setlists {
  id: Generated<number>;
  name: string;
  description: string | null;
  source_type: string;
  source_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface SetlistItems {
  id: Generated<number>;
  setlist_id: number;
  item_type: Generated<string>;
  chart_md5: string | null;
  composition_id: number | null;
  pdf_library_id: number | null;
  name: string;
  artist: string;
  charter: string | null;
  position: number;
  speed: Generated<number>;
  added_at: string;
}

export interface YoutubeAssociations {
  id: Generated<number>;
  chart_md5: string;
  youtube_url: string;
  offset_ms: Generated<number>;
  created_at: string;
}

export interface PracticeSessions {
  id: Generated<number>;
  setlist_item_id: number;
  status: string;
  started_at: string;
  ended_at: string | null;
  speed: number;
  notes: string | null;
  duration_ms: number | null;
}

export interface SongSections {
  id: Generated<number>;
  chart_md5: string;
  name: string;
  start_position: number;
  end_position: number;
  sort_order: number;
  pdf_page: number | null;
  pdf_y_offset: number | null;
}

export interface SectionProgress {
  id: Generated<number>;
  song_section_id: number;
  setlist_item_id: number;
  status: string;
  updated_at: string;
}

export interface SongAnnotations {
  id: Generated<number>;
  song_section_id: number;
  content: string;
  created_at: string;
  updated_at: string;
}

export interface TabCompositions {
  id: Generated<number>;
  title: string;
  artist: string;
  album: string;
  tempo: number;
  instrument: string;
  preview_image: string | null;
  is_saved: Generated<number>;
  saved_at: string | null;
  created_at: string;
  updated_at: string;
  score_data: ArrayBuffer;
  youtube_url: string | null;
}

export interface FretboardSessions {
  id: Generated<number>;
  drill_type: string;
  difficulty: string;
  total_questions: number;
  correct_answers: number;
  duration_ms: number;
  xp_earned: Generated<number>;
  created_at: string;
}

export interface FretboardAttempts {
  id: Generated<number>;
  session_id: number;
  drill_type: string;
  string_index: number;
  fret: number;
  expected_answer: string;
  given_answer: string | null;
  status: Generated<string>;
  response_time_ms: number;
  created_at: string;
}

export interface FretboardCards {
  id: Generated<number>;
  string_index: number;
  fret: number;
  direction: string;
  interval: Generated<number>;
  ease_factor: Generated<number>;
  repetitions: Generated<number>;
  next_review_date: string;
  last_reviewed_at: string | null;
  created_at: string;
}

export interface FillPracticeSessions {
  id: Generated<number>;
  fill_id: string;
  bpm: number;
  learned: Generated<number>;
  duration_ms: Generated<number>;
  created_at: string;
}

export interface PdfLibrary {
  id: Generated<number>;
  filename: string;
  relative_path: string;
  file_size_bytes: number;
  detected_title: string | null;
  detected_artist: string | null;
  added_at: string;
}

export interface ChartPdfs {
  id: Generated<number>;
  chart_md5: string;
  pdf_library_id: number;
  label: string | null;
  is_primary: Generated<number>;
  linked_at: string;
}

export interface EarSessions {
  id: Generated<number>;
  exercise_type: string;
  difficulty: string;
  total_questions: number;
  correct_answers: number;
  skipped_count: Generated<number>;
  duration_ms: number;
  xp_earned: Generated<number>;
  playback_mode: string;
  direction: string;
  speed: string;
  created_at: string;
}

export interface EarAttempts {
  id: Generated<number>;
  session_id: number;
  exercise_type: string;
  prompt_item: string;
  answer_context: string | null;
  expected_answer: string;
  given_answer: string | null;
  status: Generated<string>;
  response_time_ms: number;
  created_at: string;
}

export interface RepertoireCollections {
  id: Generated<number>;
  name: Generated<string>;
  description: string | null;
  color: Generated<string>;
  created_at: string;
  updated_at: string;
}

export interface RepertoireItems {
  id: Generated<number>;
  collection_id: Generated<number>;
  item_type: string;
  title: string;
  artist: string | null;
  notes: string | null;
  target_bpm: number | null;
  /** @deprecated Use saved_chart_md5 / composition_id / song_section_id instead */
  reference_type: string | null;
  /** @deprecated Use saved_chart_md5 / composition_id / song_section_id instead */
  reference_id: string | null;
  /** Typed FK: references saved_charts.md5 */
  saved_chart_md5: string | null;
  /** Typed FK: references tab_compositions.id */
  composition_id: number | null;
  /** Typed FK: references song_sections.id */
  song_section_id: number | null;
  /** Dedup key for curriculum-seeded theory cards */
  theory_source: string | null;
  interval: Generated<number>;
  ease_factor: Generated<number>;
  repetitions: Generated<number>;
  next_review_date: string;
  last_reviewed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface RepertoireReviews {
  id: Generated<number>;
  item_id: number;
  quality: number;
  interval_before: number;
  interval_after: number;
  ease_factor_before: number;
  ease_factor_after: number;
  duration_ms: number | null;
  session_notes: string | null;
  created_at: string;
}

export interface ExplorerSaves {
  id: Generated<number>;
  list_name: Generated<string>;
  artist: string;
  name: string;
  artist_normalized: string;
  name_normalized: string;
  spotify_track_uri: string | null;
  added_at: string;
}

export interface SyncMeta {
  key: string;
  value: string;
}

export interface StemAssociations {
  song_key: string;
  stem_folder_path: string;
  created_at: string;
}

export interface LearnProgress {
  id: Generated<number>;
  instrument: string;
  unit_id: string;
  lesson_id: string;
  completed_at: string;
}

export interface LearnXpLedger {
  id: Generated<number>;
  amount: number;
  source: string;
  instrument: string | null;
  lesson_id: string | null;
  earned_at: string;
  surface: string | null;
  ref_id: string | null;
  dedupe_key: string | null;
}

export interface LearnStreaks {
  id: Generated<number>;
  current_streak: number;
  longest_streak: number;
  last_active_date: string | null;
  daily_goal_target: number;
  updated_at: string;
  singleton: number; // always 1, used for UNIQUE constraint
}

export interface LearnDailyGoal {
  id: Generated<number>;
  date: string;
  xp_earned: number;
  target_xp: number;
  completed: number; // 0 or 1 (SQLite boolean)
}

export interface LessonStars {
  id: Generated<number>;
  instrument: string;
  unit_id: string;
  lesson_id: string;
  stars: number;                  // 1..3
  best_hearts_remaining: number;  // 0..MAX_HEARTS
  best_accuracy: number;          // 0..1
  first_try: number;              // 0 or 1 (SQLite boolean)
  attempts: Generated<number>;
  last_completed_at: string;
}

export interface InstrumentLevels {
  instrument: string;             // PK: 'guitar' | 'drums' | 'theory'
  cum_xp: Generated<number>;
  level: Generated<number>;
  xp_into_level: Generated<number>;
  xp_to_next: number;
  updated_at: string;
}

export interface EarnedAchievement {
  id: Generated<number>;
  achievement_id: string;       // catalog id, UNIQUE
  earned_at: string;
  meta: string | null;          // JSON
}

export interface ActiveMission {
  id: Generated<number>;
  template_id: string;
  week_start: string;           // YYYY-MM-DD (Monday, local)
  target: number;
  progress: Generated<number>;
  xp_reward: number;
  state: Generated<string>;     // 'active' | 'completed' | 'expired'
  created_at: string;
  completed_at: string | null;
}

export interface DailyPlan {
  date: string;                 // YYYY-MM-DD (PK)
  items: string;                // JSON array
  target_xp: number;
  generated_at: string;
}

export interface PracticeProgram {
  id: Generated<number>;
  title: string;
  description: string | null;
  instrument: string | null;
  status: string;          // 'draft' | 'active' | 'archived'
  started_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProgramUnit {
  id: Generated<number>;
  program_id: number;
  title: string;
  description: string | null;
  order_index: number;
  suggested_days: number | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
}

export interface UnitGoal {
  id: Generated<number>;
  unit_id: number;
  title: string;
  type: string;            // 'song' | 'tab' | 'learn_lesson' | 'exercise' | 'custom'
  ref_id: string | null;
  target: string | null;
  notes: string | null;
  order_index: number;
  completed_at: string | null;
  created_at: string;
}

export interface LessonSession {
  id: Generated<number>;
  title: string | null;
  unit_id: number | null;
  scheduled_date: string;  // YYYY-MM-DD
  scheduled_time: string | null;
  duration_minutes: number | null;
  completed_at: string | null;
  notes: string | null;
  created_at: string;
}

/**
 * Heartbeat-driven log of contiguous active app windows. One row per
 * (visible + interacting) span, separated by idle timeout or tab hide.
 * `duration_ms` accumulates from periodic 30s heartbeats. No stored `date`
 * column — query daily totals with `date(started_at) = ?`.
 */
export interface AppSessions {
  id: Generated<number>;
  started_at: string;
  ended_at: string | null;
  duration_ms: Generated<number>;
  context: Generated<string>; // CHECK-constrained: 'browse'|'lesson'|'drill'|'ear'|'repertoire'|'fill'|'rudiment'|'tab_editor'|'playbook'
}

export interface DB {
  explorer_saves: ExplorerSaves;
  chorus_charts: ChorusCharts;
  spotify_history_imports: SpotifyHistoryImports;
  chorus_metadata: ChorusMetadata;
  chorus_scan_sessions: ChorusScanSessions;
  local_charts: LocalCharts;
  spotify_album_tracks: SpotifyAlbumTracks;
  spotify_albums: SpotifyAlbums;
  spotify_history: SpotifyHistory;
  spotify_playlist_tracks: SpotifyPlaylistTracks;
  spotify_playlists: SpotifyPlaylists;
  spotify_track_chart_matches: SpotifyTrackChartMatches;
  saved_charts: SavedCharts;
  setlists: Setlists;
  setlist_items: SetlistItems;
  spotify_tracks: SpotifyTracks;
  youtube_associations: YoutubeAssociations;
  practice_sessions: PracticeSessions;
  song_sections: SongSections;
  section_progress: SectionProgress;
  song_annotations: SongAnnotations;
  tab_compositions: TabCompositions;
  fretboard_sessions: FretboardSessions;
  fretboard_attempts: FretboardAttempts;
  fretboard_cards: FretboardCards;
  fill_practice_sessions: FillPracticeSessions;
  pdf_library: PdfLibrary;
  chart_pdfs: ChartPdfs;
  ear_sessions: EarSessions;
  ear_attempts: EarAttempts;
  repertoire_collections: RepertoireCollections;
  repertoire_items: RepertoireItems;
  repertoire_reviews: RepertoireReviews;
  sync_meta: SyncMeta;
  stem_associations: StemAssociations;
  learn_progress: LearnProgress;
  learn_xp_ledger: LearnXpLedger;
  learn_streaks: LearnStreaks;
  learn_daily_goal: LearnDailyGoal;
  lesson_stars: LessonStars;
  instrument_levels: InstrumentLevels;
  earned_achievements: EarnedAchievement;
  active_missions: ActiveMission;
  daily_plan: DailyPlan;
  practice_programs: PracticeProgram;
  program_units: ProgramUnit;
  unit_goals: UnitGoal;
  lesson_sessions: LessonSession;
  app_sessions: AppSessions;
}
