/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ChorusCharts {
  album_art_md5: string | null;
  artist: string;
  artist_bucket: string | null;
  artist_normalized: string | null;
  charter: string;
  charter_normalized: string | null;
  diff_bass: number | null;
  diff_drums: number | null;
  diff_drums_real: number | null;
  diff_guitar: number | null;
  diff_keys: number | null;
  group_id: number;
  has_video_background: number;
  md5: string;
  modified_time: string;
  name: string;
  name_normalized: string | null;
  song_length: number | null;
}

export interface ChorusMetadata {
  key: string | null;
  updated_at: Generated<string>;
  value: string;
}

export interface ChorusScanSessions {
  completed_at: string | null;
  id: Generated<number | null>;
  last_chart_id: number | null;
  scan_since_time: string;
  started_at: string;
  status: string;
}

export interface LocalCharts {
  artist: string;
  artist_bucket: string | null;
  artist_normalized: string | null;
  charter: string;
  charter_normalized: string | null;
  data: string;
  id: Generated<number | null>;
  modified_time: string;
  song: string;
  song_normalized: string | null;
  updated_at: string;
}

export interface SpotifyAlbums {
  artist_name: string;
  id: string;
  name: string;
  total_tracks: Generated<number>;
  updated_at: string;
}

export interface SpotifyAlbumTracks {
  album_id: string;
  track_id: string;
  updated_at: string;
}

export interface SpotifyPlaylists {
  collaborative: Generated<number>;
  id: string;
  name: string;
  owner_display_name: string;
  owner_external_url: string;
  snapshot_id: string;
  total_tracks: Generated<number>;
  updated_at: string;
}

export interface SpotifyPlaylistTracks {
  playlist_id: string;
  track_id: string;
}

export interface SpotifyTracks {
  artist: string;
  artist_bucket: string | null;
  artist_normalized: string | null;
  id: string;
  name: string;
  name_normalized: string | null;
  updated_at: string;
}

export interface SpotifyTrackChartMatches {
  spotify_id: string;
  chart_md5: string;
  matched_at: number;
}

export interface SpotifyHistory {
  artist: string;
  artist_normalized: string;
  name: string;
  name_normalized: string;
  play_count: number;
}

export interface SavedCharts {
  md5: string;
  name: string;
  artist: string;
  charter: string;
  album_art_md5: string | null;
  diff_drums: number | null;
  diff_drums_real: number | null;
  diff_guitar: number | null;
  diff_bass: number | null;
  diff_keys: number | null;
  song_length: number | null;
  has_video_background: number;
  modified_time: string;
  saved_at: string;
  is_downloaded: Generated<number>;
  tab_url: string | null;
}

export interface Setlists {
  id: Generated<number>;
  name: string;
  description: string | null;
  source_type: string;
  source_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface SetlistItems {
  id: Generated<number>;
  setlist_id: number;
  chart_md5: string;
  name: string;
  artist: string;
  charter: string;
  position: number;
  speed: Generated<number>;
  added_at: string;
}

export interface YoutubeAssociations {
  id: Generated<number>;
  chart_md5: string;
  youtube_url: string;
  offset_ms: Generated<number>;
  created_at: string;
}

export interface PracticeSessions {
  id: Generated<number>;
  setlist_item_id: number;
  status: string;
  started_at: string;
  ended_at: string | null;
  speed: number;
  notes: string | null;
}

export interface SongSections {
  id: Generated<number>;
  chart_md5: string;
  name: string;
  start_position: number;
  end_position: number;
  sort_order: number;
  pdf_page: number | null;
  pdf_y_offset: number | null;
}

export interface SectionProgress {
  id: Generated<number>;
  song_section_id: number;
  setlist_item_id: number;
  status: string;
  updated_at: string;
}

export interface SongAnnotations {
  id: Generated<number>;
  song_section_id: number;
  content: string;
  created_at: string;
  updated_at: string;
}

export interface TabCompositions {
  id: Generated<number>;
  title: string;
  artist: string;
  album: string;
  tempo: number;
  instrument: string;
  created_at: string;
  updated_at: string;
  score_data: ArrayBuffer;
}

export interface FretboardSessions {
  id: Generated<number>;
  drill_type: string;
  difficulty: string;
  total_questions: number;
  correct_answers: number;
  duration_ms: number;
  xp_earned: Generated<number>;
  created_at: string;
}

export interface FretboardAttempts {
  id: Generated<number>;
  session_id: number;
  drill_type: string;
  string_index: number;
  fret: number;
  expected_answer: string;
  given_answer: string | null;
  status: Generated<string>;
  response_time_ms: number;
  created_at: string;
}

export interface FillPracticeSessions {
  id: Generated<number>;
  fill_id: string;
  bpm: number;
  learned: Generated<number>;
  created_at: string;
}

export interface PdfLibrary {
  id: Generated<number>;
  filename: string;
  relative_path: string;
  file_size_bytes: number;
  detected_title: string | null;
  detected_artist: string | null;
  added_at: string;
}

export interface ChartPdfs {
  id: Generated<number>;
  chart_md5: string;
  pdf_library_id: number;
  label: string | null;
  is_primary: Generated<number>;
  linked_at: string;
}

export interface DB {
  chorus_charts: ChorusCharts;
  chorus_metadata: ChorusMetadata;
  chorus_scan_sessions: ChorusScanSessions;
  local_charts: LocalCharts;
  spotify_album_tracks: SpotifyAlbumTracks;
  spotify_albums: SpotifyAlbums;
  spotify_history: SpotifyHistory;
  spotify_playlist_tracks: SpotifyPlaylistTracks;
  spotify_playlists: SpotifyPlaylists;
  spotify_track_chart_matches: SpotifyTrackChartMatches;
  saved_charts: SavedCharts;
  setlists: Setlists;
  setlist_items: SetlistItems;
  spotify_tracks: SpotifyTracks;
  youtube_associations: YoutubeAssociations;
  practice_sessions: PracticeSessions;
  song_sections: SongSections;
  section_progress: SectionProgress;
  song_annotations: SongAnnotations;
  tab_compositions: TabCompositions;
  fretboard_sessions: FretboardSessions;
  fretboard_attempts: FretboardAttempts;
  fill_practice_sessions: FillPracticeSessions;
  pdf_library: PdfLibrary;
  chart_pdfs: ChartPdfs;
}
